POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndoYXRldmVyIiwiaWQiOiI2NmQ1YmIxZjk5MjdkMzM2YTU4Njc5ODUiLCJpYXQiOjE3MjUzNjk3NjIsImV4cCI6MTcyNTM3MzM2Mn0.An6IFoW7CBxc6jX__M8UpzlEi42UOyweIBf_pBRg0tQ

{
    "title": "who knows",
    "author": "no idea",
    "url": "/api/blogs/qualia_the_purple",
    "likes": 86876
}